run:
  timeout: 5m
  issues-exit-code: 0
  build-tags:
    -
  modules-download-mode: readonly

output:
  format: checkstyle

linters:
  enable:
    - contextcheck
    - cyclop
    - errorlint
    - exhaustive
    - exportloopref
    - gofmt
    - gomnd
    - gosec
    - ifshort
    - makezero
    - misspell
    - nilerr
    - noctx
    - revive
    - tagliatelle
    - tenv
    - unconvert
    - unparam
    - wrapcheck
  disable:
    - golint
    - interfacer
    - scopelint
    - maligned

linters-settings:
  staticcheck:
    go: "1.18"