FROM golang:1.22.5-alpine3.20 AS build
ARG GITHUB_USER
ARG GITHUB_TOKEN

RUN apk add -U --no-cache gcc g++ openssh
RUN apk update && \
    apk add --no-cache git

RUN mkdir -p /root/.ssh && \
    echo "machine github.com login ${GITHUB_USER} password ${GITHUB_TOKEN}" > /root/.netrc

WORKDIR /src

COPY go.mod go.sum ./

RUN GOPRIVATE=github.com/PicPay go mod download

COPY . .

RUN CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -tags musl -ldflags="-linkmode external -w" -o bin/api cmd/api/main.go

FROM alpine:3.20

RUN apk update && \
    apk add --no-cache git

RUN addgroup -S picpay && adduser -S picpay -G picpay
WORKDIR /home/picpay/app

COPY --from=build /src/bin/api .

USER picpay
EXPOSE 8080

ENTRYPOINT ["/home/picpay/app/api"]
