FROM 289208114389.dkr.ecr.us-east-1.amazonaws.com/golang:1.21.5-alpine3.18 as build
ARG GITHUB_TOKEN
ARG GITHUB_USER

WORKDIR /src

COPY . .

RUN echo machine github.com login "$GITHUB_USER" password "$GITHUB_TOKEN" > ~/.netrc \
    ; GOPRIVATE=github.com/PicPay go mod download \
    ; CGO_ENABLED=0 go build -o bin/api cmd/api/main.go

FROM 289208114389.dkr.ecr.us-east-1.amazonaws.com/alpine:3.18.2

RUN addgroup -S picpay && adduser -S picpay -G picpay
WORKDIR /home/picpay/app

COPY --from=build /src/bin/api .

USER picpay
EXPOSE 8080

ENTRYPOINT /home/picpay/app/api
