global:
  app_stage: qa
  image:
    tag: ${artifact.buildNo}
  releaseNumber: 0
  externalSecrets:
  - name: default
    enabled: true
    type: vault
    mountPath: kubernetes-chatpp-use1-hom
    path: cross_products/hom/env
    dataFrom:
      - secretFile: ms-chatpicpay-websocket-handler-api
  - name: secrets
    enabled: true
    type: vault
    mountPath: kubernetes-chatpp-use1-hom
    path: cross_products/hom/scrt
    dataFrom:
      - secretFile: ms-chatpicpay-websocket-handler-api

picpay-ms-v2:
  apis:
    - name: api
      workload: chatpp
      envFrom:
      - secretRef:
          name: envs
      - secretRef:
          name: envs-secrets
      health:
        path: /health
      readiness:
        initialDelaySeconds: 1
        periodSeconds: 5
        successThreshold: 1
        failureThreshold: 3
        timeoutSeconds: 5
      liveness:
        initialDelaySeconds: 1
        periodSeconds: 5
        successThreshold: 1
        failureThreshold: 3
        timeoutSeconds: 5
      hpa:
        enabled: true
        max: 3
        min: 1
        targetCPU: 80
      containerPort: 8080
      image:
        repositoryURI: 289208114389.dkr.ecr.us-east-1.amazonaws.com/picpay-dev/ms-chatpicpay-websocket-handler-api
      ingress:
        - enabled: true
          type: internal-microservices
          hosts:
            - hostname: ms-chatpicpay-websocket-handler-api.ms.qa
              path: "/"
      podDisruptionBudget:
        enabled: false
      limits_memory: 100Mi
      limits_cpu: 100m
      requests_cpu: 100m
      requests_memory: 100Mi
      service:
        enabled: true
        port: 80
        targetPort: 8080
