// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
	context "context"

	logger "github.com/PicPay/lib-go-logger/v2"
	mock "github.com/stretchr/testify/mock"
)

// SessionClienter is an autogenerated mock type for the SessionClienter type
type SessionClienter struct {
	mock.Mock
}

// ValidateMobileToken provides a mock function with given fields: ctx, token, correlationId, log
func (_m *SessionClienter) ValidateMobileToken(ctx context.Context, token string, correlationId string, log *logger.Logger) (string, error) {
	ret := _m.Called(ctx, token, correlationId, log)

	if len(ret) == 0 {
		panic("no return value specified for ValidateMobileToken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *logger.Logger) (string, error)); ok {
		return rf(ctx, token, correlationId, log)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *logger.Logger) string); ok {
		r0 = rf(ctx, token, correlationId, log)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, *logger.Logger) error); ok {
		r1 = rf(ctx, token, correlationId, log)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewSessionClienter creates a new instance of SessionClienter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSessionClienter(t interface {
	mock.TestingT
	Cleanup(func())
}) *SessionClienter {
	mock := &SessionClienter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
