// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
	context "context"

	logger "github.com/PicPay/lib-go-logger/v2"
	mock "github.com/stretchr/testify/mock"
)

// SubscribeServicer is an autogenerated mock type for the SubscribeServicer type
type SubscribeServicer struct {
	mock.Mock
}

// SubscribeAsync provides a mock function with given fields: ctx, eventsChan, log
func (_m *SubscribeServicer) SubscribeAsync(ctx context.Context, eventsChan chan []byte, log *logger.Logger) error {
	ret := _m.Called(ctx, eventsChan, log)

	if len(ret) == 0 {
		panic("no return value specified for SubscribeAsync")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, chan []byte, *logger.Logger) error); ok {
		r0 = rf(ctx, eventsChan, log)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewSubscribeServicer creates a new instance of SubscribeServicer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSubscribeServicer(t interface {
	mock.TestingT
	Cleanup(func())
}) *SubscribeServicer {
	mock := &SubscribeServicer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
